jdbc.driver=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
jdbc.url=jdbc:log4jdbc:mysql://localhost:3306/scoula_db
jdbc.username=root
jdbc.password=8500


weather.url=http://api.openweathermap.org/data/2.5/weather
weather.api_key=eb79317145a27345c99c04030a569695
weather.icon_url=http://openweathermap.org/img/w/%s.png